/* Automatically generated by wasm2c */
#ifndef E_TXT_H_GENERATED_
#define E_TXT_H_GENERATED_

#include "wasm-rt.h"

#include <stdint.h>

#ifndef WASM_RT_CORE_TYPES_DEFINED
#define WASM_RT_CORE_TYPES_DEFINED
typedef uint8_t u8;
typedef int8_t s8;
typedef uint16_t u16;
typedef int16_t s16;
typedef uint32_t u32;
typedef int32_t s32;
typedef uint64_t u64;
typedef int64_t s64;
typedef float f32;
typedef double f64;
#endif

#ifdef __cplusplus
extern "C" {
#endif

struct w2c_imports;

typedef struct w2c_a {
  struct w2c_imports* w2c_imports_instance;
} w2c_a;

void wasm2c_a_instantiate(w2c_a*, struct w2c_imports*);
void wasm2c_a_free(w2c_a*);
wasm_rt_func_type_t wasm2c_a_get_func_type(uint32_t param_count, uint32_t result_count, ...);

/* import: 'imports' 'log' */
void w2c_imports_log(struct w2c_imports*, u32);

/* export: 'start' */
void w2c_a_start(w2c_a*);

#ifdef __cplusplus
}
#endif

#endif  /* E_TXT_H_GENERATED_ */
